=== nickbethke/botc-editor/src/schema/riverPreset.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"additionalProperties": false,
	"$id": "River Preset Schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"width": {
			"type": "number",
			"minimum": 1,
			"maximum": 20
		},
		"height": {
			"type": "number",
			"minimum": 1,
			"maximum": 20
		},
		"data": {
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"position": {
						"type": "array",
						"items": {
							"type": "number"
						},
						"minItems": 2,
						"maxItems": 2
					},
					"direction": {
						"type": "string",
						"enum": [
							"NORTH",
							"SOUTH",
							"EAST",
							"WEST"
						]
					}
				},
				"required": [
					"position",
					"direction"
				]
			}
		}
	},
	"required": [
		"data",
		"name",
		"width",
		"height"
	]
}

=== nickbethke/botc-editor/assets/defaultPresets/rivers/L  6x6.json
{
    "width": 6,
    "height": 6,
    "data": [
        {
            "position": [
                0,
                0
            ],
            "direction": "SOUTH"
        },
        {
            "position": [
                0,
                1
            ],
            "direction": "SOUTH"
        },
        {
            "position": [
                0,
                2
            ],
            "direction": "SOUTH"
        },
        {
            "position": [
                0,
                3
            ],
            "direction": "SOUTH"
        },
        {
            "position": [
                0,
                4
            ],
            "direction": "SOUTH"
        },
        {
            "position": [
                0,
                5
            ],
            "direction": "EAST"
        },
        {
            "position": [
                1,
                5
            ],
            "direction": "EAST"
        },
        {
            "position": [
                2,
                5
            ],
            "direction": "EAST"
        },
        {
            "position": [
                3,
                5
            ],
            "direction": "EAST"
        },
        {
            "position": [
                4,
                5
            ],
            "direction": "EAST"
        },
        {
            "position": [
                5,
                5
            ],
            "direction": "EAST"
        }
    ],
    "name": "L  6x6"
}

=== nickbethke/botc-editor/assets/defaultPresets/rivers/5x5.json
{
	"width": 5,
	"height": 5,
	"data": [
		{
			"position": [
				0,
				0
			],
			"direction": "SOUTH"
		},
		{
			"position": [
				0,
				1
			],
			"direction": "SOUTH"
		},
		{
			"position": [
				0,
				2
			],
			"direction": "SOUTH"
		},
		{
			"position": [
				0,
				3
			],
			"direction": "SOUTH"
		},
		{
			"position": [
				0,
				4
			],
			"direction": "EAST"
		},
		{
			"position": [
				1,
				4
			],
			"direction": "EAST"
		},
		{
			"position": [
				2,
				4
			],
			"direction": "EAST"
		},
		{
			"position": [
				3,
				4
			],
			"direction": "EAST"
		},
		{
			"position": [
				4,
				4
			],
			"direction": "NORTH"
		},
		{
			"position": [
				4,
				3
			],
			"direction": "NORTH"
		},
		{
			"position": [
				4,
				2
			],
			"direction": "NORTH"
		},
		{
			"position": [
				4,
				1
			],
			"direction": "NORTH"
		},
		{
			"position": [
				4,
				0
			],
			"direction": "WEST"
		},
		{
			"position": [
				3,
				0
			],
			"direction": "WEST"
		},
		{
			"position": [
				2,
				0
			],
			"direction": "WEST"
		},
		{
			"position": [
				1,
				0
			],
			"direction": "WEST"
		}
	],
	"name": "5x5 Kreis"
}
